# Generated by Django 2.1.7 on 2019-06-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_auto_20190604_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('email', models.EmailField(max_length=255, verbose_name='邮箱')),
                ('url', models.URLField(blank=True, verbose_name='')),
                ('text', models.TextField(verbose_name='')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=True, to='blog.Post')),
            ],
            options={
                'verbose_name_plural': '评论表',
            },
        ),
    ]
